name = "common"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = "1.0.1"
lustre = ">= 4.2.5 and < 5.0.0"
lustre_ui = ">= 0.6.0 and < 1.0.0"
decipher = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.3.2 and < 2.0.0"
